from pathlib import Path


# ============================================================
# GENERATED CONFIGURATION
# ============================================================
# DO NOT EDIT THIS FILE MANUALLY.
# Edit config.json using config_gui.py instead.
# ============================================================


# PROJECT
PROJECT_NAME = 'RA3 Crystallography'


# ROOT DIRECTORIES
ROOT_DIRS = [
    Path('path/to/data'),
]


# DATASET SEARCH
SEARCH_STRING = 'RA3'
CASE_SENSITIVE = False
SEARCH_RECURSION_DEPTH = 1


# PROCESSING LIMIT
MAX_FOLDERS_TO_PROCESS = None


# OUTPUT
OUTPUT_DIR = Path('path/to/output')
OUTPUT_PREFIX = SEARCH_STRING + '_summary'
ADD_TIMESTAMP_TO_FILENAME = True
TIMESTAMP_FORMAT = '%d%m%y%H%M'


# RODHYPIX
RODHYPIX_FOLDER_NAME = 'frames'
RODHYPIX_EXTENSION = '.rodhypix'
RODHYPIX_RECURSIVE = False
FIRST_RODHYPIX_ONLY = True


# INS FILE
INS_STRUCT_FOLDER = 'struct'
INS_OLEX_PREFIX = 'olex2_'
INS_AUTO_SUFFIX = '_auto'
INS_EXTENSION = '.ins'
INS_RECURSIVE = False
FIRST_INS_ONLY = True


# UNIT CELL
IGNORE_CELL_WAVELENGTH = True


# CLUSTERING
LENGTH_TOLERANCE = 0.25
ANGLE_TOLERANCE = 0.5
UNIT_CELL_SOURCE = 'cap'
CLUSTERING_METHOD = 'reduced_cell'


# CAP
CAP_ENABLED = True
CAP_PEAK_FINDING = True
CAP_MULTICRYSTAL_INDEXING = True
CAP_UNIT_CELL_REFINEMENT = True
TWIN_MULTICRYSTAL_INDEXING_COMMAND = 'um ttt'
SMART_PEAK_HUNTING_COMMAND = 'ph snogui_pars 1000 20 1 0 2 2 10 10 0 0 1 0 0.0 1000.0'
CAP_PAR_PREFIX_PREFERENCE = ['wit_', 'pre_', '']


# CCDC
CCDC_ENABLED = False
CCDC_SEARCH_MODE = 'reduced_cell'


# GEMMI
GEMMI_ENABLED = True
GEMMI_REDUCTION_METHOD = 'buerger'


# FOLDER SIZE
SIZE_UNIT = 'MB'


# DEBUG
DEBUG = True
DEBUG_SEARCH = True
DEBUG_RODHYPIX = True
DEBUG_INS = True
DEBUG_CELL = True
DEBUG_SIZE = True
DEBUG_CAP = True
DEBUG_CCDC = True
DEBUG_GEMMI = True
DEBUG_PHASE = True


# EXCEL
EXCEL_SHEET_NAME = 'Summary'
EXCEL_DATE_FORMAT = 'yyyy-mm-dd hh:mm:ss'
EXCEL_SIZE_FORMAT = '0.00'
EXCEL_CELL_FORMAT = '0.000000'
EXCEL_FREEZE_PANES = 'A2'


# PHASE COLOURS
PHASE_COLOURS = [
    'FFFF00',
    '00FF00',
    '00FFFF',
    'FF00FF',
    'FFA500',
    'ADD8E6',
    '90EE90',
    'DDA0DD',
    'F4A460',
    'FFB6C1',
    'D3D3D3',
    'FFD700',
    '98FB98',
    '87CEEB',
    'EE82EE',
]
