from __future__ import annotations

import json
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
CONFIG_JSON = BASE_DIR / "config.json"
CONFIG_PY = BASE_DIR / "config.py"


def generate_config(data: dict) -> None:
    s = data["search"]
    o = data["output"]
    r = data["rodhypix"]
    i = data["ins"]
    u = data["unit_cell"]
    c = data["clustering"]
    cap = data["cap"]
    ccdc = data["ccdc"]
    g = data["gemmi"]
    z = data["size"]
    d = data["debug"]
    x = data["excel"]

    roots = "\n".join(f"    Path({p!r})," for p in s["root_dirs"])
    colours = "\n".join(f"    {c!r}," for c in data["phase_colours"])
    par = ", ".join(repr(p) for p in cap["par_prefix_preference"])

    output_prefix = (
        "SEARCH_STRING + '_summary'"
        if o["output_prefix"] == "SEARCH_STRING + '_summary'"
        else repr(o["output_prefix"])
    )

    text = """from pathlib import Path


# ============================================================
# GENERATED CONFIGURATION
# ============================================================
# DO NOT EDIT THIS FILE MANUALLY.
# Edit config.json using config_gui.py instead.
# ============================================================


# PROJECT
PROJECT_NAME = {project!r}


# ROOT DIRECTORIES
ROOT_DIRS = [
{roots}
]


# DATASET SEARCH
SEARCH_STRING = {search!r}
CASE_SENSITIVE = {case!r}
SEARCH_RECURSION_DEPTH = {depth!r}


# PROCESSING LIMIT
MAX_FOLDERS_TO_PROCESS = {maxfolders!r}


# OUTPUT
OUTPUT_DIR = Path({output_dir!r})
OUTPUT_PREFIX = {output_prefix}
ADD_TIMESTAMP_TO_FILENAME = {timestamp!r}
TIMESTAMP_FORMAT = {timestamp_format!r}


# RODHYPIX
RODHYPIX_FOLDER_NAME = {rod_folder!r}
RODHYPIX_EXTENSION = {rod_ext!r}
RODHYPIX_RECURSIVE = {rod_recursive!r}
FIRST_RODHYPIX_ONLY = {rod_first!r}


# INS FILE
INS_STRUCT_FOLDER = {ins_struct!r}
INS_OLEX_PREFIX = {ins_prefix!r}
INS_AUTO_SUFFIX = {ins_suffix!r}
INS_EXTENSION = {ins_ext!r}
INS_RECURSIVE = {ins_recursive!r}
FIRST_INS_ONLY = {ins_first!r}


# UNIT CELL
IGNORE_CELL_WAVELENGTH = {ignore_wavelength!r}


# CLUSTERING
LENGTH_TOLERANCE = {length!r}
ANGLE_TOLERANCE = {angle!r}
UNIT_CELL_SOURCE = {uc_source!r}
CLUSTERING_METHOD = {cluster_method!r}


# CAP
CAP_ENABLED = {cap_enabled!r}
CAP_PEAK_FINDING = {cap_peak!r}
CAP_MULTICRYSTAL_INDEXING = {cap_multi!r}
CAP_UNIT_CELL_REFINEMENT = {cap_refine!r}
TWIN_MULTICRYSTAL_INDEXING_COMMAND = {indexing!r}
SMART_PEAK_HUNTING_COMMAND = {peak_command!r}
CAP_PAR_PREFIX_PREFERENCE = [{par}]


# CCDC
CCDC_ENABLED = {ccdc_enabled!r}
CCDC_SEARCH_MODE = {ccdc_mode!r}


# GEMMI
GEMMI_ENABLED = {gemmi_enabled!r}
GEMMI_REDUCTION_METHOD = {gemmi_method!r}


# FOLDER SIZE
SIZE_UNIT = {size_unit!r}


# DEBUG
DEBUG = {debug_enabled!r}
DEBUG_SEARCH = {debug_search!r}
DEBUG_RODHYPIX = {debug_rodhypix!r}
DEBUG_INS = {debug_ins!r}
DEBUG_CELL = {debug_cell!r}
DEBUG_SIZE = {debug_size!r}
DEBUG_CAP = {debug_cap!r}
DEBUG_CCDC = {debug_ccdc!r}
DEBUG_GEMMI = {debug_gemmi!r}
DEBUG_PHASE = {debug_phase!r}


# EXCEL
EXCEL_SHEET_NAME = {sheet!r}
EXCEL_DATE_FORMAT = {date_format!r}
EXCEL_SIZE_FORMAT = {size_format!r}
EXCEL_CELL_FORMAT = {cell_format!r}
EXCEL_FREEZE_PANES = {freeze!r}


# PHASE COLOURS
PHASE_COLOURS = [
{colours}
]
""".format(
        project=data["project"]["name"], roots=roots,
        search=s["search_string"], case=s["case_sensitive"],
        depth=s["recursion_depth"], maxfolders=s["max_folders"],
        output_dir=o["output_dir"], output_prefix=output_prefix,
        timestamp=o["add_timestamp_to_filename"],
        timestamp_format=o["timestamp_format"],
        rod_folder=r["folder_name"], rod_ext=r["extension"],
        rod_recursive=r["recursive"], rod_first=r["first_only"],
        ins_struct=i["struct_folder"], ins_prefix=i["olex_prefix"],
        ins_suffix=i["auto_suffix"], ins_ext=i["extension"],
        ins_recursive=i["recursive"], ins_first=i["first_only"],
        ignore_wavelength=u["ignore_wavelength"],
        length=c["length_tolerance"], angle=c["angle_tolerance"],
        uc_source=c["unit_cell_source"], cluster_method=c["method"],
        cap_enabled=cap["enabled"], cap_peak=cap["peak_finding"],
        cap_multi=cap["multicrystal_indexing"],
        cap_refine=cap["unit_cell_refinement"],
        indexing=cap["indexing_command"],
        peak_command=cap["smart_peak_hunting_command"],
        par=par,
        ccdc_enabled=ccdc["enabled"], ccdc_mode=ccdc["search_mode"],
        gemmi_enabled=g["enabled"], gemmi_method=g["reduction_method"],
        size_unit=z["unit"],
        debug_enabled=d["enabled"], debug_search=d["search"],
        debug_rodhypix=d["rodhypix"], debug_ins=d["ins"],
        debug_cell=d["cell"], debug_size=d["size"],
        debug_cap=d["cap"], debug_ccdc=d["ccdc"],
        debug_gemmi=d["gemmi"], debug_phase=d["phase"],
        sheet=x["sheet_name"], date_format=x["date_format"],
        size_format=x["size_format"], cell_format=x["cell_format"],
        freeze=x["freeze_panes"], colours=colours,
    )
    CONFIG_PY.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    with CONFIG_JSON.open("r", encoding="utf-8") as f:
        generate_config(json.load(f))
    print(f"Generated {CONFIG_PY}")
